/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideFigure: typeof import('./src/components/components/AsideFigure.vue')['default']
    BigFigure: typeof import('./src/components/components/BigFigure.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElText: typeof import('element-plus/es')['ElText']
    HighEnergyTimeChart: typeof import('./src/components/charts/HighEnergyTimeChart.vue')['default']
    MainTopBar: typeof import('./src/components/components/MainTopBar.vue')['default']
    MidBar: typeof import('./src/components/components/MidBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentimentAnalysisChart: typeof import('./src/components/charts/SentimentAnalysisChart.vue')['default']
    SpatiotemporalChart: typeof import('./src/components/charts/SpatiotemporalChart.vue')['default']
  }
}
